title: deepfake yanderify
description: FOR YUE
template:
  repo: deepfake-yanderify-template
  name: deepfake-yanderify
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
